#!/bin/bash

function gcr(){
      git checkout --track "$1"
}

function gc(){
      output=$(git checkout "$1")

      noBranch=$(echo $output | grep "error: pathspec '.*' did not match any file(s) known to git")
      if [[ "$noBranch" == "0" ]]; then
        git branch "$1"
        git branch --set-upstream-to=origin/"$1" "$1"
        exit 0
      fi

      alreadyOnBranch=$(echo $output | grep "Already on '.*'")
      if [[ "$alreadyOnBranch" == "0" ]]; then
        git fetch
        git pull
        exit 0
      fi
}

function gs(){
        git status
}

function gh(){
    cd /c/Users/mdoerksen/source/repos
    cd "$1"
}

function gd(){
        git diff
}

function gbn(){
        git branch "$1"
        git checkout "$1"
}

function gb(){
        git branch
}

function dps(){
      if [ -z "$1" ]; then
        docker ps
      else
        docker ps $args[0]
      fi
}

function di(){
      docker images
}

function dl(){
      docker logs "$1"
}

function dc(){
      docker container "$@"
}

function da(){
      docker attach "$1"
}

function gpo() {
        confirmArg="$1"
        if [ "$confirmArg" == "-y" ]; then
          branchName=$(git branch | grep '\* ' | awk '{print $2}')
          echo "Pushing changes to GitHub under branch: $branchName"
          git push origin "$branchName"
        else
          echo "You must add -y to the gpo command in order to push changes automatically."
        fi
}

function dependencyscan() {
  path=$(pwd)
  projectRootFolderName
  dropFolder="/Drop/Debug/x64/"
  /hillock/XboxShare/ShowDependencies.cmd
}

function dna() {
    dotnet clean
    dotnet restore
    dotnet build
    dotnet test
}

function dnc() {
    dotnet nuget locals all --clear
    dotnet restore
    dotnet build
}
